# Generated by Django 4.2 on 2025-08-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_transaction_id_alter_transaction_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('description',)},
        ),
    ]
